/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!
// MARK: - FooTest22
protocol FooTest22DependencyResolver {
    var fuu: Array<FuuTest22.Params<String>> { get }
}
final class FooTest22DependencyContainer: FooTest22DependencyResolver {
    let fuu: Array<FuuTest22.Params<String>>
    init(fuu: Array<FuuTest22.Params<String>>) {
        self.fuu = fuu
    }
}
