/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!
// MARK: - FooTest10
protocol FooTest10DependencyResolver {
    var fuu: FuuTest10<String> { get }
}
final class FooTest10DependencyContainer: FooTest10DependencyResolver {
    private var _fuu: FuuTest10<String>?
    var fuu: FuuTest10<String> {
        if let value = _fuu { return value }
        let value = FuuTest10<String>()
        _fuu = value
        return value
    }
    init() {
        _ = fuu
    }
}
