/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - LoggerTest1

protocol LoggerTest1DependencyResolver: AnyObject {
    var logEngine: LogEngineTest1 { get }
}

final class LoggerTest1DependencyContainer: LoggerTest1DependencyResolver {

    private var _logEngine: Optional<LogEngineTest1> = nil
    var logEngine: LogEngineTest1 {
        if let value: LogEngineTest1 = _logEngine {
            return value
        }
        let value: LogEngineTest1 = LogEngineTest1()
        _logEngine = value
        return value
    }

    init() { _ = logEngine }
}

// MARK: - ManagerTest1

protocol ManagerTest1DependencyResolver: AnyObject {
    var logger: LoggerTest1 { get }
}

final class ManagerTest1DependencyContainer: ManagerTest1DependencyResolver {

    private var _logger: Optional<LoggerTest1> = nil
    var logger: LoggerTest1 {
        if let value: LoggerTest1 = _logger {
            return value
        }
        let value: LoggerTest1 = LoggerTest1(injecting: LoggerTest1DependencyContainer())
        _logger = value
        return value
    }

    init() { _ = logger }
}

