/// This file is generated by Weaver 0.12.1
/// DO NOT EDIT!
// MARK: - FooTest4
protocol FooTest4DependencyResolver {
    var fuu: FuuProtocolTest4 { get }
}
final class FooTest4DependencyContainer: FooTest4DependencyResolver {
    private var _fuu: FuuProtocolTest4?
    var fuu: FuuProtocolTest4 {
        if let value = _fuu { return value }
        let value = FuuTest4.make(self)
        _fuu = value
        return value
    }
    init() {
        _ = fuu
    }
}
