/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - FooTest21

protocol FooTest21DependencyResolver: AnyObject {
    var fuu: FuuTest21.Params<String> { get }
}

final class FooTest21DependencyContainer: FooTest21DependencyResolver {

    private var _fuu: Optional<FuuTest21.Params<String>> = nil
    var fuu: FuuTest21.Params<String> {
        if let value: FuuTest21.Params<String> = _fuu {
            return value
        }
        let value: FuuTest21.Params<String> = FuuTest21.Params<String>()
        _fuu = value
        return value
    }

    init() { _ = fuu }
}

