import Foundation

/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - FooTest16

@objc protocol FooTest16DependencyResolver: AnyObject {
    var fuu: FuuTest16 { get }
}

@objc final class FooTest16DependencyContainer: NSObject, FooTest16DependencyResolver {

    private var _fuu: Optional<FuuTest16> = nil
    var fuu: FuuTest16 {
        if let value: FuuTest16 = _fuu {
            return value
        }
        let value: FuuTest16 = FuuTest16()
        _fuu = value
        return value
    }

    override init() {
        super.init()
        _ = fuu
    }
}

protocol FooTest16ObjCDependencyInjectable: AnyObject {
}

