/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!
import Foundation
// MARK: - FooTest20
typealias FooTest20DependencyResolver = FuuTest20Resolver
final class FooTest20DependencyContainer: NSObject, FooTest20DependencyResolver {
    private var _fuu: FuuTest20?
    var fuu: FuuTest20 {
        if let value = _fuu { return value }
        let value = FuuTest20()
        _fuu = value
        return value
    }
    override init() {
        super.init()
        _ = fuu
    }
}
protocol FooTest20ObjCDependencyInjectable {}
// MARK: - Detailed Resolvers
@objc protocol FuuTest20Resolver {
    var fuu: FuuTest20 { get }
}
