/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!
// MARK: - FooTest21
protocol FooTest21DependencyResolver {
    var fuu: FuuTest21.Params<String> { get }
}
final class FooTest21DependencyContainer: FooTest21DependencyResolver {
    private var _fuu: FuuTest21.Params<String>?
    var fuu: FuuTest21.Params<String> {
        if let value = _fuu { return value }
        let value = FuuTest21.Params<String>()
        _fuu = value
        return value
    }
    init() {
        _ = fuu
    }
}
