/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - FooTest4

protocol FooTest4DependencyResolver: AnyObject {
    var fuu: FuuProtocolTest4 { get }
}

final class FooTest4DependencyContainer: FooTest4DependencyResolver {

    private var _fuu: Optional<FuuProtocolTest4> = nil
    var fuu: FuuProtocolTest4 {
        if let value: FuuProtocolTest4 = _fuu {
            return value
        }
        let value: FuuProtocolTest4 = FuuTest4.make(self)
        _fuu = value
        return value
    }

    init() { _ = fuu }
}

