/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!
// MARK: - FooTest23
protocol FooTest23DependencyResolver {
    var fuu: Dictionary<FuuTest23.Key<String>, FuuTest23.Params<String>> { get }
}
final class FooTest23DependencyContainer: FooTest23DependencyResolver {
    let fuu: Dictionary<FuuTest23.Key<String>, FuuTest23.Params<String>>
    init(fuu: Dictionary<FuuTest23.Key<String>, FuuTest23.Params<String>>) {
        self.fuu = fuu
    }
}
