/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - FooTest10

protocol FooTest10DependencyResolver: AnyObject {
    var fuu: FuuTest10<String> { get }
}

final class FooTest10DependencyContainer: FooTest10DependencyResolver {

    private var _fuu: Optional<FuuTest10<String>> = nil
    var fuu: FuuTest10<String> {
        if let value: FuuTest10<String> = _fuu {
            return value
        }
        let value: FuuTest10<String> = FuuTest10<String>()
        _fuu = value
        return value
    }

    init() { _ = fuu }
}

