/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!
// MARK: - FooTest21
protocol FooTest21DependencyResolver {
    var foo: Test21Nest.Test21Type<.Test21Type> { get }
}
final class FooTest21DependencyContainer: FooTest21DependencyResolver {
    let foo: Test21Nest.Test21Type<.Test21Type>
    init(foo: Test21Nest.Test21Type<.Test21Type>) {
        self.foo = foo
    }
}
