/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - FooTest6

protocol FooTest6DependencyResolver: AnyObject {
    var fuu: FuuProtocolTest6 { get }
}

final class FooTest6DependencyContainer: FooTest6DependencyResolver {

    private var _fuu: Optional<FuuProtocolTest6> = nil
    var fuu: FuuProtocolTest6 {
        if let value: FuuProtocolTest6 = _fuu {
            return value
        }
        let value: FuuProtocolTest6 = FuuTest6()
        _fuu = value
        return value
    }

    init() { _ = fuu }
}

