/// This file is generated by Weaver 0.12.4
/// DO NOT EDIT!

// MARK: - FooTest5

protocol FooTest5DependencyResolver: AnyObject {
    var fii: FiiTest5 { get }
}

final class FooTest5DependencyContainer: FooTest5DependencyResolver {

    private var _fii: Optional<FiiTest5> = nil
    var fii: FiiTest5 {
        if let value: FiiTest5 = _fii {
            return value
        }
        let value: FiiTest5 = FiiTest5()
        _fii = value
        return value
    }

    init() { _ = fii }
}

// MARK: - FuuTest5

protocol FuuTest5DependencyResolver: AnyObject {
    var fii: FiiProtocolTest5 { get }
}

final class FuuTest5DependencyContainer: FuuTest5DependencyResolver {

    private var _fii: Optional<FiiProtocolTest5> = nil
    var fii: FiiProtocolTest5 {
        if let value: FiiProtocolTest5 = _fii {
            return value
        }
        let value: FiiProtocolTest5 = FiiTest5()
        _fii = value
        return value
    }

    init() { _ = fii }
}

