/// This file is generated by Weaver 0.10.2
/// DO NOT EDIT!
// MARK: - FooTest13
protocol FooTest13DependencyResolver {
    var fuu: FuuTest12 { get }
}
final class FooTest13DependencyContainer: FooTest13DependencyResolver {
    private var _fuu: FuuTest12?
    var fuu: FuuTest12 {
        if let value = _fuu { return value }
        let value = FuuTest12()
        _fuu = value
        return value
    }
    init() {
        _ = fuu
    }
}
